### ISSUE TITLE
Condition failing

### ISSUE THREAD

**Issue by prashantvidja** [frikky/Shuffle#321] opened 2021-03-31 16:08 UTC
**Describe the bug**
Condition failing - I have set conditions for check output and based on diverting workflow. I have used "contains" and "equal to".

**To Reproduce**
1. create a workflow
2. set the condition to check output 
3. Run workflow

**Expected behavior**
The condition should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/26060662/113175298-e7e91b80-9268-11eb-8de2-65fba5d7ca56.png)

**Debug logs**
```
Nothing found in the log.
```

**Comment by frikky** [comment] 2021-03-31 16:10
Hey! 

What do you mean with step 2: "set the condition to check output"? 
Can you provide some exact information I can pass through? 

Thanks

**Comment by prashantvidja** [comment] 2021-04-01 03:24
Hi,

Yes, I am using custom apps. I have set conditions between two nodes to check the output of one node.

Thanks

**Comment by frikky** [comment] 2021-04-03 11:33
Hey! To clarify:

What is the value of the nodes and the condition _exactly_ so that I can reproduce it? 
Everything seems to be working fine here with contains, equals and everything else.

PS: Please try to [upgrade to 0.8.71](https://github.com/frikky/Shuffle/blob/master/docker-compose.yml). We changed the format of Conditions that FAIL previously to say "SKIPPED", which changed a bit of how our backend handles things as well.

**Comment by frikky** [comment] 2021-04-05 11:00
Any update here btw? :)

**Comment by prashantvidja** [comment] 2021-04-05 11:36
I will test it and update you

**Comment by frikky** [comment] 2021-04-12 19:28
Closing as this was fixed in 0.8.71 and now expanded upon in [0.8.73](https://github.com/frikky/Shuffle/blob/master/docker-compose.yml)

**Closed by frikky** 2021-04-12 19:28 UTC
Labels: 0.9.0, Unverified, bug
